### ISSUE TITLE
please how to generate the file "scaler.pkl"?

### ISSUE THREAD

**Issue by moshangqingfeng** [emilbjornson/power-allocation-cell-free#4]
please how to generate the file "scaler.pkl"?

**Comment by NowhereMan-042** [comment]
@moshangqingfeng Have you been able to sort out the issue?

**Comment by NowhereMan-042** [comment]
I have found the solution to this issue. You have to uncomment the last line of the 'Distributed_FFNN' file -  

> dump(scaler, open(models_filename + 'scaler.pkl', 'wb'))

 and then run this program. This will generate the scaler.pkl file in the folder named 'pAssignmodels'.

**Comment by moshangqingfeng** [comment]
@NowhereMan-042  I have been sorted out this.Thank you.

**Comment by NowhereMan-042** [comment]
[like]  0422062510 - Samit Khan reacted to your message:
________________________________
